volumes:
  db:

services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=arciphant
      - POSTGRES_PASSWORD=arciphantpw
      - POSTGRES_DB=arciphant-sample-project
