package ch.ergon.arciphant.core

import ch.ergon.arciphant.ArciphantPlugin.Companion.logger
import org.gradle.api.initialization.ProjectDescriptor
import java.io.File

/**
 * Creates the folders of the Gradle projects generated by Arciphant. Gradle 9+ requires the folder of every
 * included project to exist. Source set folders are never created: they are not required by Gradle and
 * their location may be customized (e.g. via `customizeAllComponents`) in the source set layout.
 */
internal class ProjectFolderCreator(
    private val settings: GlobalSettings,
    private val rootProject: ProjectDescriptor
) {

    fun createProjectFoldersIfNotExists(projectConfigs: List<GradleProjectConfig>) {
        if (!settings.disableProjectFolderCreation) {
            projectConfigs.forEach { createProjectFolderIfNotExists(it) }
        }
    }

    private fun createProjectFolderIfNotExists(projectConfig: GradleProjectConfig) {
        rootProject.projectDir.resolve(projectConfig.folderPath).createDirectoryIfNotExists()
    }

    private val GradleProjectConfig.folderPath get() = path.folderPath

    private val GradleProjectPath.folderPath get() = projectNames.joinToString("/")

    private fun File.createDirectoryIfNotExists() {
        if (mkdirs()) {
            logger.info("Created project folder $absolutePath")
        }
    }
}
